### ISSUE TITLE
Fix broken image in user creation confirmation email

### ISSUE THREAD

**Issue by bartwr** [urbanlink/haagsemakers.nl#4]
## How to reproduce

1. Sign up for an account on haagsemakers.nl.
2. Open the confirmation email *Welcome to Haagse Makers Account*
3. Watch the broken image icon.

## How to fix

- Replace the URL below to a working one.

> `http://www.haagsemakers.nl/assets/images/logos/hm-vignet-vlak.png`

- OR upload `hm-vignet-vlak.png` to `/assets/images/logos/`

___

![screenshot](http://bartroorda.nl/upimg/201512-jkd897j3/s-20160214-134942.png)

**Comment by avanderpluijm** [comment]
Fixed by changing image link.
